### PR TITLE
Disable back button on login. Fix camera erasing location bug. closes #193 closes #153

### LINKED ISSUE #153: We can get into the app using the back button on the Login page
Maybe implement the onBackPressed() function

### LINKED ISSUE #193: When creating or editing a habit event, taking a photo from the camera erases the location from the location field
and it's annoying!

### PR DESCRIPTION
**Pull request by Jie-F**
Simple fix

### CODE REVIEW

File: code/HabitTracker/app/src/main/java/com/example/habittracker/activities/eventlist/EventDetailActivity.java [hunk 1]
```diff
@@ -66,6 +66,7 @@
     private Habit habit;
     private static final int PICK_IMAGE_REQUEST = 1;
     private static final int TAKE_PHOTO_REQUEST = 2;
+    private static final int SELECT_LOCATION_REQUEST = 3;
```
Comment (johnzhang27) [inline code/HabitTracker/app/src/main/java/com/example/habittracker/activities/eventlist/EventDetailActivity.java:69]: You have to change the result code in map activity as well. This won't work until you changed the result code in MapActivity.

**Review by johnzhang27 — APPROVED** [review]
